github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    addCheck: true
    addComment: false

image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 80
    onOpen: ignore
  
tasks:
  - name: Env Pkgs
    init: npm install -g newman
  - name: Node Start
    init: npm install
    command: node server.js
  - name: Mongo Start
    command: mkdir -p /workspace/data && mongod --dbpath /workspace/data
    openMode: split-right